version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: UCT
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/database"
  schedule:
    interval: monthly
    timezone: UCT
  open-pull-requests-limit: 99
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    day: sunday
    timezone: UCT
  open-pull-requests-limit: 99
- package-ecosystem: gomod
  directory: "/tools/autograph-monitor"
  schedule:
    interval: monthly
    day: sunday
    timezone: UCT
  open-pull-requests-limit: 99
